export const GO_TO_WALLET = "GO_TO_WALLET";
export const GO_TO_RNS_DASHBOARD = "GO_TO_RNS_DASHBOARD";

export const WEB3_PROVIDER_OPENED = "WEB3_PROVIDER_OPENED";

export const LOAD_WEB3 = "LOAD_WEB3";
export const SAVE_WEB3 = "SAVE_WEB3";

export const GET_BALANCE_TIMER = "GET_BALANCE_TIMER";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_RBTC_BALANCE = "UPDATE_RBTC_BALANCE";
export const RNS_CHECK = "RNS_CHECK";