export const GO_TO_WALLET = "GO_TO_WALLET";
export const GO_TO_RNS_DASHBOARD = "GO_TO_RNS_DASHBOARD";

export const WEB3_PROVIDER_OPENED = "WEB3_PROVIDER_OPENED";

export const LOAD_WEB3 = "LOAD_WEB3";
export const SAVE_WEB3 = "SAVE_WEB3";

export const GET_BALANCE_TIMER = "GET_BALANCE_TIMER";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_RBTC_BALANCE = "UPDATE_RBTC_BALANCE";
export const RNS_CHECK = "RNS_CHECK";
export const RNS_CHECK_OWNER_RESULT = "RNS_CHECK_OWNER_RESULT";
export const RNS_DOMAIN_RESOLVER_CHECKED = "RNS_DOMAIN_RESOLVER_CHECKED";
export const RNS_DOMAIN_SET_RESOLVER = "RNS_DOMAIN_SET_RESOLVER";
export const RNS_DOMAIN_SET_RESOLVER_DONE = "RNS_DOMAIN_SET_RESOLVER_DONE";
export const RNS_DOMAIN_ADDR_RECEIVED = "RNS_DOMAIN_ADDR_RECEIVED"

//RNS page displayed
export const RNS_DOMAIN_DETAIL = "RNS_DOMAIN_DETAIL"
export const RNS_DASHBOARD = "RNS_DASHBOARD"